name: CI/CD Pipeline for Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        # Fetch the latest code from the repository

      # Step 2: Set Up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        # Configure the Node.js environment for matrix testing

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install
        env:
          cache: npm
        # Install project dependencies and enable caching for npm

      # Step 4: Run Tests
      - name: Run Tests
        run: npm test
        # Execute the test suite to validate the code