name: CI/CD Pipeline for Node.js (Express)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test # Example environment variable, replace with actual values as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        env:
          # Add environment variables required for npm install, if any
          API_KEY: ${{ secrets.API_KEY }}

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        env:
          # Add environment variables required for tests
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}

      # Optional: Notifications (e.g., Slack or email)
      - name: Notify team
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          text: 'Pipeline failed for ${{ github.repository }} on branch ${{ github.ref }}'