name: CI/CD Pipeline for Node.js Project

# Trigger the pipeline on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    # Define the environment for the build job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
        # No additional parameters needed for this step

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        # This command installs all dependencies listed in package.json

  test:
    # Define the environment for the test job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Run tests using Jest
      - name: Run tests
        run: npm test
        # This command executes the test suite defined in the project